### ISSUE TITLE
page 11 - checklist - ensure that user changes reflect in state

### ISSUE THREAD

**Issue by hagiosofori** [nengeBota/Online-Forms#23]
- [x] cover page
- [x] application form
- [x] certificate of incorporation
- [x] certificate to commence business
- [x] company regulations
- [x] signed hsse policy and objectives
- [x] current audited financial reports or projected revenue from upstream oil industry
- [x] valid tax clearance certificate
- [x] vat certificate
- [x] original ssnit clearance certificate
- [x] something important that's missing
- [x] copies of other regulatory certs
- [x] copy of application pack receipt
